#!/bin/bash

# script to fetch toolchain source tar using ci.netsurf-browser.org as a cache

# Usage fetchsrc <target> <source> <upstream> <output>

NSSRV="http://ci.netsurf-browser.org/toolchain/"

wget -q -O ${4} ${NSSRV}/${1}/${2}
if [ $? -ne 0 ];then
    wget -q -O ${4} ${3}
    if [ $? -ne 0 ];then
        rm ${4}
	return 1
    fi
fi
