#ifndef INLINE4_AMIGAINPUT_H
#define INLINE4_AMIGAINPUT_H

/*
** This file was auto generated by idltool 53.16.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef AMIGAINPUT_AMIGAINPUT_H
#include <amigainput/amigainput.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#include <interfaces/AmigaInput.h>

/* Inline macros for Interface "main" */
#define GetError(ctx) IAIN_->GetError((ctx)) 
#define GetErrorString(error_code) IAIN_->GetErrorString((error_code)) 
#define CreateContext(api_version, tags) IAIN_->CreateContext((api_version), (tags)) 
#define DeleteContext(ctx) IAIN_->DeleteContext((ctx)) 
#define EnumDevices(ctx, enumfunc, user_data) IAIN_->EnumDevices((ctx), (enumfunc), (user_data)) 
#define Query(ctx, device_id, qParameter, qArg, result, result_length) IAIN_->Query((ctx), (device_id), (qParameter), (qArg), (result), (result_length)) 
#define ObtainDevice(ctx, device_id) IAIN_->ObtainDevice((ctx), (device_id)) 
#define ReleaseDevice(ctx, handle) IAIN_->ReleaseDevice((ctx), (handle)) 
#define SetDeviceParameter(ctx, handle, dParameter, dArg) IAIN_->SetDeviceParameter((ctx), (handle), (dParameter), (dArg)) 
#define GetEvent(ctx) IAIN_->GetEvent((ctx)) 
#define FreeEvent(ctx, event) IAIN_->FreeEvent((ctx), (event)) 
#define ReadDevice(ctx, handle, data) IAIN_->ReadDevice((ctx), (handle), (data)) 
#define Set(ctx, tags) IAIN_->Set((ctx), (tags)) 
#define RequestDevice(ctx, tags) IAIN_->RequestDevice((ctx), (tags)) 
#define FreeRequest(ctx, result) IAIN_->FreeRequest((ctx), (result)) 

#endif /* INLINE4_AMIGAINPUT_H */
