#ifndef INLINE4_EXPANSION_H
#define INLINE4_EXPANSION_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Copyright (C) 2003-2021 Trevor Dickinson
**
** It provides compatibility to AmigaOS 3.x style library
** calls by substituting functions.
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>

#include <expansion/pci.h>
#include <expansion/expansion.h>
#include <expansion/configvars.h>
#include <dos/dos.h>
#include <dos/dosextens.h>
#include <dos/filehandler.h>
#include <interfaces/expansion.h>

/* Inline macros for Interface "main" */
#define AddConfigDev(configDev) IExpansion->AddConfigDev((configDev))
#define AddBootNode(bootPri, flags, deviceNode, configDev) IExpansion->AddBootNode((bootPri), (flags), (deviceNode), (configDev))
#define AllocBoardMem(slotSpec) IExpansion->AllocBoardMem((slotSpec))
#define AllocConfigDev() IExpansion->AllocConfigDev()
#define AllocExpansionMem(numSlots, slotAlign) IExpansion->AllocExpansionMem((numSlots), (slotAlign))
#define ConfigBoard(board, configDev) IExpansion->ConfigBoard((board), (configDev))
#define ConfigChain(baseAddr) IExpansion->ConfigChain((baseAddr))
#define FindConfigDev(oldConfigDev, manufacturer, product) IExpansion->FindConfigDev((oldConfigDev), (manufacturer), (product))
#define FreeBoardMem(startSlot, slotSpec) IExpansion->FreeBoardMem((startSlot), (slotSpec))
#define FreeConfigDev(configDev) IExpansion->FreeConfigDev((configDev))
#define FreeExpansionMem(startSlot, numSlots) IExpansion->FreeExpansionMem((startSlot), (numSlots))
#define ReadExpansionByte(board, offset) IExpansion->ReadExpansionByte((board), (offset))
#define ReadExpansionRom(board, configDev) IExpansion->ReadExpansionRom((board), (configDev))
#define RemConfigDev(configDev) IExpansion->RemConfigDev((configDev))
#define WriteExpansionByte(board, offset, byte) IExpansion->WriteExpansionByte((board), (offset), (byte))
#define ObtainConfigBinding() IExpansion->ObtainConfigBinding()
#define ReleaseConfigBinding() IExpansion->ReleaseConfigBinding()
#define SetCurrentBinding(currentBinding, bindingSize) IExpansion->SetCurrentBinding((currentBinding), (bindingSize))
#define GetCurrentBinding(currentBinding, bindingSize) IExpansion->GetCurrentBinding((currentBinding), (bindingSize))
#define MakeDosNode(parmPacket) IExpansion->MakeDosNode((parmPacket))
#define AddDosNode(bootPri, flags, deviceNode) IExpansion->AddDosNode((bootPri), (flags), (deviceNode))
#define WriteExpansionWord(board, offset, word) IExpansion->WriteExpansionWord((board), (offset), (word))
#define GetMachineInfo(tagList) IExpansion->GetMachineInfo((tagList))
#define GetMachineInfoTags(...) IExpansion->GetMachineInfoTags(__VA_ARGS__)

#endif /* INLINE4_EXPANSION_H */
