#ifndef INLINE4_UTILITY_H
#define INLINE4_UTILITY_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Copyright (C) 2003-2021 Trevor Dickinson
**
** It provides compatibility to AmigaOS 3.x style library
** calls by substituting functions.
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>

#include <utility/utility.h>

/* Inline macros for Interface "main" */
#define AllocateTagItems(numTags) IUtility->AllocateTagItems((numTags))
#define ApplyTagChanges(list, changeList) IUtility->ApplyTagChanges((list), (changeList))
#define CloneTagItems(original) IUtility->CloneTagItems((original))
#define FilterTagChanges(changeList, originalList, apply) IUtility->FilterTagChanges((changeList), (originalList), (apply))
#define FilterTagItems(taglist, filterArray, logic) IUtility->FilterTagItems((taglist), (filterArray), (logic))
#define FindTagItem(tagValue, tagList) IUtility->FindTagItem((tagValue), (tagList))
#define FreeTagItems(tagList) IUtility->FreeTagItems((tagList))
#define GetTagData(tagValue, defaultVal, tagList) IUtility->GetTagData((tagValue), (defaultVal), (tagList))
#define MapTags(tagList, mapList, mapType) IUtility->MapTags((tagList), (mapList), (mapType))
#define NextTagItem(tags) IUtility->NextTagItem((tags))
#define PackBoolTags(initialFlags, tagList, boolMap) IUtility->PackBoolTags((initialFlags), (tagList), (boolMap))
#define RefreshTagItemClones(clone, original) IUtility->RefreshTagItemClones((clone), (original))
#define TagInArray(tagValue, tagArray) IUtility->TagInArray((tagValue), (tagArray))
#define CallHookPkt(hook, object, message) IUtility->CallHookPkt((hook), (object), (message))
#define CallHook(hook, ...) IUtility->CallHook((hook), __VA_ARGS__)
#define AddNamedObject(nameSpace, object) IUtility->AddNamedObject((nameSpace), (object))
#define AllocNamedObjectA(name, tags) IUtility->AllocNamedObjectA((name), (tags))
#define AllocNamedObject(...) IUtility->AllocNamedObject(__VA_ARGS__)
#define AttemptRemNamedObject(object) IUtility->AttemptRemNamedObject((object))
#define FindNamedObject(name_space, name, previous_object) IUtility->FindNamedObject((name_space), (name), (previous_object))
#define FreeNamedObject(obj) IUtility->FreeNamedObject((obj))
#define NamedObjectName(obj) IUtility->NamedObjectName((obj))
#define ReleaseNamedObject(obj) IUtility->ReleaseNamedObject((obj))
#define RemNamedObject(obj, message) IUtility->RemNamedObject((obj), (message))
#define Amiga2Date(date_amiga, cd) IUtility->Amiga2Date((date_amiga), (cd))
#define CheckDate(date) IUtility->CheckDate((date))
#define Date2Amiga(date) IUtility->Date2Amiga((date))
#define CreateSkipList(hook, max_levels) IUtility->CreateSkipList((hook), (max_levels))
#define DeleteSkipList(skipList) IUtility->DeleteSkipList((skipList))
#define FindSkipNode(skipList, key) IUtility->FindSkipNode((skipList), (key))
#define GetFirstSkipNode(skipList) IUtility->GetFirstSkipNode((skipList))
#define GetNextSkipNode(skipList, node) IUtility->GetNextSkipNode((skipList), (node))
#define InsertSkipNode(skipList, key, dataSize) IUtility->InsertSkipNode((skipList), (key), (dataSize))
#define RemoveSkipNode(skipList, key) IUtility->RemoveSkipNode((skipList), (key))
#define CreateSplayTree(compareHook) IUtility->CreateSplayTree((compareHook))
#define DeleteSplayTree(splayTree) IUtility->DeleteSplayTree((splayTree))
#define FindSplayNode(splayTree, key) IUtility->FindSplayNode((splayTree), (key))
#define InsertSplayNode(splayTree, key, date_size) IUtility->InsertSplayNode((splayTree), (key), (date_size))
#define RemoveSplayNode(splayTree, key) IUtility->RemoveSplayNode((splayTree), (key))
#define FindNameNC(list, name) IUtility->FindNameNC((list), (name))
#define GetUniqueID() IUtility->GetUniqueID()
#define MessageDigest_SHA_Final(shas) IUtility->MessageDigest_SHA_Final((shas))
#define MessageDigest_SHA_Init(shas) IUtility->MessageDigest_SHA_Init((shas))
#define MessageDigest_SHA_Update(shas, data, num_bytes) IUtility->MessageDigest_SHA_Update((shas), (data), (num_bytes))
#define PackStructureTags(pack, pack_table, tagList) IUtility->PackStructureTags((pack), (pack_table), (tagList))
#define UnpackStructureTags(pack, pack_table, tagList) IUtility->UnpackStructureTags((pack), (pack_table), (tagList))
#define Random(state) IUtility->Random((state))
#define SetMem(destination, fillChar, length) IUtility->SetMem((destination), (fillChar), (length))
#define Stricmp(s1, s2) IUtility->Stricmp((s1), (s2))
#define Strlcpy(dst, src, size) IUtility->Strlcpy((dst), (src), (size))
#define Strlcat(dst, src, size) IUtility->Strlcat((dst), (src), (size))
#define Strnicmp(s1, s2, n) IUtility->Strnicmp((s1), (s2), (n))
#define ToLower(c) IUtility->ToLower((c))
#define ToUpper(c) IUtility->ToUpper((c))
#define VASPrintf(fmt, args) IUtility->VASPrintf((fmt), (args))
#define ASPrintf(...) IUtility->ASPrintf(__VA_ARGS__)
#define VSNPrintf(buffer, bufferSize, fmt, args) IUtility->VSNPrintf((buffer), (bufferSize), (fmt), (args))
#define SNPrintf(buffer, bufferSize, ...) IUtility->SNPrintf((buffer), (bufferSize), __VA_ARGS__)
#define ClearMem(destination, size) IUtility->ClearMem((destination), (size))
#define MoveMem(source, destination, size) IUtility->MoveMem((source), (destination), (size))
#define Strlen(string) IUtility->Strlen((string))
#define UTF8toUCS4(utf8_source, ucs4_destination, ucs4_destination_size, flags) IUtility->UTF8toUCS4((utf8_source), (ucs4_destination), (ucs4_destination_size), (flags))
#define UCS4toUTF8(ucs4_source, utf8_destination, utf8_destination_size, flags) IUtility->UCS4toUTF8((ucs4_source), (utf8_destination), (utf8_destination_size), (flags))
#define UTF8Strnicmp(utf8string1, utf8string2, maxUCSchars) IUtility->UTF8Strnicmp((utf8string1), (utf8string2), (maxUCSchars))
#define UTF8Stricmp(utf8string1, utf8string2) IUtility->UTF8Stricmp((utf8string1), (utf8string2))
#define UTF8Count(utf8string, validate) IUtility->UTF8Count((utf8string), (validate))
#define UCS4Count(ucs4string, validate) IUtility->UCS4Count((ucs4string), (validate))
#define UTF8Encode(ucs4, buffer, bufsize, flags) IUtility->UTF8Encode((ucs4), (buffer), (bufsize), (flags))
#define UTF8Decode(utf8_pptr, flags) IUtility->UTF8Decode((utf8_pptr), (flags))
#define UCS4ToLower(ucs4in) IUtility->UCS4ToLower((ucs4in))
#define UCS4ToUpper(ucs4in) IUtility->UCS4ToUpper((ucs4in))
#define UCS4Valid(ucs4) IUtility->UCS4Valid((ucs4))
#define SortList(list, cmpHook) IUtility->SortList((list), (cmpHook))
#define SortMinList(list, cmpHook) IUtility->SortMinList((list), (cmpHook))

#endif /* INLINE4_UTILITY_H */
