#ifndef PROTO_ACPI_H
#define PROTO_ACPI_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2015 Trevor Dickinson
**
** Prototype/inline/pragma header file combo.
*/

#include <resources/acpi.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * ACPIBase;
  #else
   extern struct Library * ACPIBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * ACPIBase;
  #else
   extern struct Library * ACPIBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/acpi.h>
 #ifdef __USE_INLINE__
  #include <inline4/acpi.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_ACPI_PROTOS_H
  #define CLIB_ACPI_PROTOS_H 1
 #endif /* CLIB_ACPI_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::ACPIIFace * IACPI;
  #else
   extern struct ACPIIFace * IACPI;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_ACPI_PROTOS_H
  #include <clib/acpi_protos.h>
 #endif /* CLIB_ACPI_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/acpi.h>
  #else /* __PPC__ */
   #include <ppcinline/acpi.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/acpi_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/acpi_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_ACPI_H */
