#ifndef PROTO_EXEC_H
#define PROTO_EXEC_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2003-2022 Trevor Dickinson
**
** Prototype/inline/pragma header file combo.
*/

#include <utility/utility.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * SysBase;
  #else
   extern struct Library * SysBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::ExecBase * SysBase;
  #else
   extern struct ExecBase * SysBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/exec.h>
 #ifdef __USE_INLINE__
  #include <inline4/exec.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_EXEC_PROTOS_H
  #define CLIB_EXEC_PROTOS_H 1
 #endif /* CLIB_EXEC_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::ExecIFace * IExec;
  #else
   extern struct ExecIFace * IExec;
  #endif
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::MMUIFace * IMMU;
  #else
   extern struct MMUIFace * IMMU;
  #endif
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::DebugIFace * IDebug;
  #else
   extern struct DebugIFace * IDebug;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_EXEC_PROTOS_H
  #include <clib/exec_protos.h>
 #endif /* CLIB_EXEC_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/exec.h>
  #else /* __PPC__ */
   #include <ppcinline/exec.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/exec_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/exec_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_EXEC_H */
