#ifndef PROTO_EXPANSION_H
#define PROTO_EXPANSION_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2003-2021 Trevor Dickinson
**
** Prototype/inline/pragma header file combo.
*/

#include <expansion/pci.h>
#include <expansion/expansion.h>
#include <expansion/configvars.h>
#include <dos/dos.h>
#include <dos/dosextens.h>
#include <dos/filehandler.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * ExpansionBase;
  #else
   extern struct Library * ExpansionBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::ExpansionBase * ExpansionBase;
  #else
   extern struct ExpansionBase * ExpansionBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/expansion.h>
 #ifdef __USE_INLINE__
  #include <inline4/expansion.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_EXPANSION_PROTOS_H
  #define CLIB_EXPANSION_PROTOS_H 1
 #endif /* CLIB_EXPANSION_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::ExpansionIFace * IExpansion;
  #else
   extern struct ExpansionIFace * IExpansion;
  #endif
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::PCIIFace * IPCI;
  #else
   extern struct PCIIFace * IPCI;
  #endif
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::PCIDevice * IPCIDev;
  #else
   extern struct PCIDevice * IPCIDev;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_EXPANSION_PROTOS_H
  #include <clib/expansion_protos.h>
 #endif /* CLIB_EXPANSION_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/expansion.h>
  #else /* __PPC__ */
   #include <ppcinline/expansion.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/expansion_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/expansion_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_EXPANSION_H */
