#ifndef PROTO_FSLDMA_H
#define PROTO_FSLDMA_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2019,2021 Trevor Dickinson
**
** Prototype/inline/pragma header file combo.
*/

#include <interfaces/fsldma.h>
#include <resources/fsldma.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * fslDMABase;
  #else
   extern struct Library * fslDMABase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * fslDMABase;
  #else
   extern struct Library * fslDMABase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/fsldma.h>
 #ifdef __USE_INLINE__
  #include <inline4/fsldma.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_FSLDMA_PROTOS_H
  #define CLIB_FSLDMA_PROTOS_H 1
 #endif /* CLIB_FSLDMA_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::fslDMAIFace * IfslDMA;
  #else
   extern struct fslDMAIFace * IfslDMA;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_FSLDMA_PROTOS_H
  #include <clib/fsldma_protos.h>
 #endif /* CLIB_FSLDMA_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/fsldma.h>
  #else /* __PPC__ */
   #include <ppcinline/fsldma.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/fsldma_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/fsldma_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_FSLDMA_H */
