#ifndef PROTO_I2C_H
#define PROTO_I2C_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2019-2020 Trevor Dickinson
**
** Prototype/inline/pragma header file combo.
*/

#include <interfaces/i2c.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * I2CBase;
  #else
   extern struct Library * I2CBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * I2CBase;
  #else
   extern struct Library * I2CBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/i2c.h>
 #ifdef __USE_INLINE__
  #include <inline4/i2c.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_I2C_PROTOS_H
  #define CLIB_I2C_PROTOS_H 1
 #endif /* CLIB_I2C_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::I2CResourceIFace * II2CRes;
  #else
   extern struct I2CResourceIFace * II2CRes;
  #endif
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::I2CIFace * II2CBus;
  #else
   extern struct I2CIFace * II2CBus;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_I2C_PROTOS_H
  #include <clib/i2c_protos.h>
 #endif /* CLIB_I2C_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/i2c.h>
  #else /* __PPC__ */
   #include <ppcinline/i2c.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/i2c_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/i2c_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_I2C_H */
