#ifndef PROTO_PERFORMANCEMONITOR_H
#define PROTO_PERFORMANCEMONITOR_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2004 Trevor Dickinson
**
** Prototype/inline/pragma header file combo.
*/

#include <interfaces/performancemonitor.h>
#include <resources/performancemonitor.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * PMBase;
  #else
   extern struct Library * PMBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * PMBase;
  #else
   extern struct Library * PMBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/performancemonitor.h>
 #ifdef __USE_INLINE__
  #include <inline4/performancemonitor.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_PERFORMANCEMONITOR_PROTOS_H
  #define CLIB_PERFORMANCEMONITOR_PROTOS_H 1
 #endif /* CLIB_PERFORMANCEMONITOR_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::PerformanceMonitorIFace * IPM;
  #else
   extern struct PerformanceMonitorIFace * IPM;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_PERFORMANCEMONITOR_PROTOS_H
  #include <clib/performancemonitor_protos.h>
 #endif /* CLIB_PERFORMANCEMONITOR_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/performancemonitor.h>
  #else /* __PPC__ */
   #include <ppcinline/performancemonitor.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/performancemonitor_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/performancemonitor_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_PERFORMANCEMONITOR_H */
