#ifndef PROTO_UTILITY_H
#define PROTO_UTILITY_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2003-2021 Trevor Dickinson
**
** Prototype/inline/pragma header file combo.
*/

#include <utility/utility.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * UtilityBase;
  #else
   extern struct Library * UtilityBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::UtilityBase * UtilityBase;
  #else
   extern struct UtilityBase * UtilityBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/utility.h>
 #ifdef __USE_INLINE__
  #include <inline4/utility.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_UTILITY_PROTOS_H
  #define CLIB_UTILITY_PROTOS_H 1
 #endif /* CLIB_UTILITY_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::UtilityIFace * IUtility;
  #else
   extern struct UtilityIFace * IUtility;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_UTILITY_PROTOS_H
  #include <clib/utility_protos.h>
 #endif /* CLIB_UTILITY_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/utility.h>
  #else /* __PPC__ */
   #include <ppcinline/utility.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/utility_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/utility_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_UTILITY_H */
