#ifndef ACPI_INTERFACE_DEF_H
#define ACPI_INTERFACE_DEF_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2015 Trevor Dickinson
**
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>

#include <resources/acpi.h>

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct ACPIIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct ACPIIFace *Self);
	uint32 APICALL (*Release)(struct ACPIIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	void APICALL (*GetAttr)(struct ACPIIFace *Self, uint32 attr, APTR storage);
	void APICALL (*SetAttr)(struct ACPIIFace *Self, uint32 attr, CONST_APTR value);
	void APICALL (*Shutdown)(struct ACPIIFace *Self);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* ACPI_INTERFACE_DEF_H */
