#ifndef AMIGAINPUT_INTERFACE_DEF_H
#define AMIGAINPUT_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.16.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef AMIGAINPUT_AMIGAINPUT_H
#include <amigainput/amigainput.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct AIN_IFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct AIN_IFace *Self);
	uint32 APICALL (*Release)(struct AIN_IFace *Self);
	void APICALL (*Expunge)(struct AIN_IFace *Self);
	struct Interface * APICALL (*Clone)(struct AIN_IFace *Self);
	uint32 APICALL (*GetError)(struct AIN_IFace *Self, APTR ctx);
	STRPTR APICALL (*GetErrorString)(struct AIN_IFace *Self, uint32 error_code);
	APTR APICALL (*CreateContext)(struct AIN_IFace *Self, uint32 api_version, struct TagItem * tags);
	void APICALL (*DeleteContext)(struct AIN_IFace *Self, APTR ctx);
	BOOL APICALL (*EnumDevices)(struct AIN_IFace *Self, APTR ctx, APTR enumfunc, APTR user_data);
	BOOL APICALL (*Query)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceID device_id, uint32 qParameter, uint32 qArg, APTR result, uint32 result_length);
	AIN_DeviceHandle * APICALL (*ObtainDevice)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceID device_id);
	void APICALL (*ReleaseDevice)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceHandle * handle);
	BOOL APICALL (*SetDeviceParameter)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceHandle * handle, uint32 dParameter, uint32 dArg);
	AIN_InputEvent * APICALL (*GetEvent)(struct AIN_IFace *Self, APTR ctx);
	void APICALL (*FreeEvent)(struct AIN_IFace *Self, APTR ctx, AIN_InputEvent * event);
	BOOL APICALL (*ReadDevice)(struct AIN_IFace *Self, APTR ctx, AIN_DeviceHandle * handle, APTR * data);
	BOOL APICALL (*Set)(struct AIN_IFace *Self, APTR ctx, struct TagItem * tags);
	AIN_RequesterResult * APICALL (*RequestDevice)(struct AIN_IFace *Self, APTR ctx, struct TagItem * tags);
	void APICALL (*FreeRequest)(struct AIN_IFace *Self, APTR ctx, AIN_RequesterResult * result);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* AMIGAINPUT_INTERFACE_DEF_H */
