#ifndef FSLDMA_INTERFACE_DEF_H
#define FSLDMA_INTERFACE_DEF_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2019,2021 Trevor Dickinson
**
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>

#include <interfaces/fsldma.h>
#include <resources/fsldma.h>

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct fslDMAIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct fslDMAIFace *Self);
	uint32 APICALL (*Release)(struct fslDMAIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	BOOL APICALL (*CopyMemDMA)(struct fslDMAIFace *Self, CONST_APTR pSourceBuffer, APTR pDestBuffer, uint32 lBufferSize);
	BOOL APICALL (*CopyMemDMATagList)(struct fslDMAIFace *Self, CONST_APTR pSourceBuffer, APTR pDestBuffer, uint32 lBufferSize, const struct TagItem * Tags);
	BOOL APICALL (*CopyMemDMATags)(struct fslDMAIFace *Self, CONST_APTR pSourceBuffer, APTR pDestBuffer, uint32 lBufferSize, ...);
	BOOL APICALL (*StartDMAChain)(struct fslDMAIFace *Self, struct dma_link_descriptor * pDMALinkArray);
	BOOL APICALL (*StartDMAChainTagList)(struct fslDMAIFace *Self, struct dma_link_descriptor * pDMALinkArray, const struct TagItem * Tags);
	BOOL APICALL (*StartDMAChainTags)(struct fslDMAIFace *Self, struct dma_link_descriptor * pDMALinkArray, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* FSLDMA_INTERFACE_DEF_H */
