#ifndef I2C_INTERFACE_DEF_H
#define I2C_INTERFACE_DEF_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2019-2020 Trevor Dickinson
**
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>

#include <interfaces/i2c.h>

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct I2CResourceIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct I2CResourceIFace *Self);
	uint32 APICALL (*Release)(struct I2CResourceIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	struct I2CIFace * APICALL (*GetBusByNumber)(struct I2CResourceIFace *Self, uint32 num);
	struct I2CIFace * APICALL (*GetBusByName)(struct I2CResourceIFace *Self, CONST_STRPTR name);
};

struct I2CIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct I2CIFace *Self);
	uint32 APICALL (*Release)(struct I2CIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	BOOL APICALL (*Probe)(struct I2CIFace *Self, uint32 address);
	BOOL APICALL (*SetSpeed)(struct I2CIFace *Self, uint32 speed);
	int32 APICALL (*Read)(struct I2CIFace *Self, uint32 chip, uint32 addr, uint8 * buffer, uint32 bufferLen);
	int32 APICALL (*ReadTagList)(struct I2CIFace *Self, uint32 chip, uint32 addr, uint8 * buffer, uint32 bufferLen, struct TagItem * tags);
	int32 APICALL (*ReadTags)(struct I2CIFace *Self, uint32 chip, uint32 addr, uint8 * buffer, uint32 bufferLen, ...);
	int32 APICALL (*Write)(struct I2CIFace *Self, uint32 chip, uint32 addr, uint8 * buffer, uint32 bufferLen);
	int32 APICALL (*WriteTagList)(struct I2CIFace *Self, uint32 chip, uint32 addr, uint8 * buffer, uint32 bufferLen, struct TagItem * tags);
	int32 APICALL (*WriteTags)(struct I2CIFace *Self, uint32 chip, uint32 addr, uint8 * buffer, uint32 bufferLen, ...);
	STRPTR APICALL (*GetName)(struct I2CIFace *Self);
	uint32 APICALL (*GetDeviceId)(struct I2CIFace *Self, uint32 address);
	void APICALL (*Lock)(struct I2CIFace *Self);
	void APICALL (*Unlock)(struct I2CIFace *Self);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* I2C_INTERFACE_DEF_H */
