#ifndef PERFORMANCEMONITOR_INTERFACE_DEF_H
#define PERFORMANCEMONITOR_INTERFACE_DEF_H

/*
** This file was machine generated by idltool.py 54.6.
** Do not edit.
**
** Copyright (C) 2004 Trevor Dickinson
**
*/

#include <exec/types.h>
#include <exec/exec.h>
#include <exec/interfaces.h>

#include <interfaces/performancemonitor.h>
#include <resources/performancemonitor.h>

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct PerformanceMonitorIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct PerformanceMonitorIFace *Self);
	uint32 APICALL (*Release)(struct PerformanceMonitorIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	uint32 APICALL (*CounterGet)(struct PerformanceMonitorIFace *Self, uint32 whatCount);
	uint32 APICALL (*CounterMatch)(struct PerformanceMonitorIFace *Self, uint32 itemNum);
	BOOL APICALL (*CounterControl)(struct PerformanceMonitorIFace *Self, uint32 whichCount, int32 value, uint32 what);
	uint32 APICALL (*EventControl)(struct PerformanceMonitorIFace *Self, struct TagItem * tagList);
	uint32 APICALL (*EventControlTags)(struct PerformanceMonitorIFace *Self, ...);
	struct Interrupt * APICALL (*SetInterruptVector)(struct PerformanceMonitorIFace *Self, uint32 event, struct Interrupt * handler);
	void APICALL (*Mark)(struct PerformanceMonitorIFace *Self, struct Task * task);
	void APICALL (*Unmark)(struct PerformanceMonitorIFace *Self, struct Task * task);
	uint32 APICALL (*MonitorControl)(struct PerformanceMonitorIFace *Self, struct TagItem * tagList);
	uint32 APICALL (*MonitorControlTags)(struct PerformanceMonitorIFace *Self, ...);
	uint32 APICALL (*Query)(struct PerformanceMonitorIFace *Self, uint32 item);
	void APICALL (*SetSampledAddress)(struct PerformanceMonitorIFace *Self, APTR addr);
	APTR APICALL (*GetSampledAddress)(struct PerformanceMonitorIFace *Self);
	void APICALL (*SetBreakpoint)(struct PerformanceMonitorIFace *Self, uint32 type, APTR instAddr, uint32 instMask, BOOL except);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* PERFORMANCEMONITOR_INTERFACE_DEF_H */
