#ifndef SCREENBLANKER_INTERFACE_DEF_H
#define SCREENBLANKER_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.16.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif
#ifndef PROTO_BLANKERMODULE_H
#include <proto/blankermodule.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct ScreenBlankerIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct ScreenBlankerIFace *Self);
	uint32 APICALL (*Release)(struct ScreenBlankerIFace *Self);
	void APICALL (*Expunge)(struct ScreenBlankerIFace *Self);
	struct IScreenBlanker * APICALL (*Clone)(struct ScreenBlankerIFace *Self);
	BOOL APICALL (*OpenBlankerModuleA)(struct ScreenBlankerIFace *Self, CONST_STRPTR name, struct TagItem * tags);
	BOOL APICALL (*OpenBlankerModule)(struct ScreenBlankerIFace *Self, CONST_STRPTR name, ...);
	void APICALL (*CloseBlankerModule)(struct ScreenBlankerIFace *Self);
	BOOL APICALL (*SetBlankingMode)(struct ScreenBlankerIFace *Self, uint32 mode);
	uint32 APICALL (*SetScreenBlankerAttrsA)(struct ScreenBlankerIFace *Self, struct TagItem * tags);
	uint32 APICALL (*SetScreenBlankerAttrs)(struct ScreenBlankerIFace *Self, ...);
	uint32 APICALL (*GetScreenBlankerAttrsA)(struct ScreenBlankerIFace *Self, struct TagItem * tags);
	uint32 APICALL (*GetScreenBlankerAttrs)(struct ScreenBlankerIFace *Self, ...);
	void APICALL (*LogPuts)(struct ScreenBlankerIFace *Self, int32 err, CONST_STRPTR context, CONST_STRPTR msg);
	uint32 APICALL (*LogFmtA)(struct ScreenBlankerIFace *Self, int32 err, CONST_STRPTR context, CONST_STRPTR msg, uint32 * args);
	uint32 APICALL (*LogFmt)(struct ScreenBlankerIFace *Self, int32 err, CONST_STRPTR context, CONST_STRPTR msg, ...);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* SCREENBLANKER_INTERFACE_DEF_H */
