#ifndef PRAGMA_EXEC_H
#define PRAGMA_EXEC_H
/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Copyright (C) 2003-2022 Trevor Dickinson
**
** Aztec `C' style pragma header file wrapper
**
*/

#ifdef __amigaos4__
#error Include <proto/> header files, not <pragma/> header files in AmigaOS 4.
#endif

#ifndef   PRAGMAS_EXEC_PRAGMAS_H
#include <pragmas/exec_pragmas.h>
#endif

#endif /* PRAGMA_EXEC_H */
