#ifndef PRAGMA_EXPANSION_H
#define PRAGMA_EXPANSION_H
/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Copyright (C) 2003-2021 Trevor Dickinson
**
** Aztec `C' style pragma header file wrapper
**
*/

#ifdef __amigaos4__
#error Include <proto/> header files, not <pragma/> header files in AmigaOS 4.
#endif

#ifndef   PRAGMAS_EXPANSION_PRAGMAS_H
#include <pragmas/expansion_pragmas.h>
#endif

#endif /* PRAGMA_EXPANSION_H */
