#  Example with Gcc with TOS environnement.
#  One can use GCCSHELL too

CC      = gcc
CFLAGS  = -O2 -I..\..\include -I..\libs
LDFLAGS = -L..\..\lib\gcc281 -lldg -lwindom -lgem
OBJECTS = client.o exlibbnd.o popupbnd.o

all: client.app

client.app: $(OBJECTS)
	$(CC) $^ -o $@ $(LDFLAGS)
	strip $@

exlibbnd.o: ..\libs\exlibbnd.c
	$(CC) -c $^ -o $@ $(CFLAGS)

popupbnd.o: ..\libs\popupbnd.c
	$(CC) -c $^ -o $@ $(CFLAGS)

clean:
	$(RM) -f *.o

