#include "oslib_licence.h"

const char oslib_license[] =
  "OSLib---efficient, type-safe, transparent, extensible,\n"
  "register-safe API coverage of RISC OS\n"
  "\n"
  "Copyright (c) 1994-2012 Jonathan Coxhead and OSLib maintainers\n"
  "\n"
  "Licence:\n"
  "\n"
  "   OSLib is free software; you can redistribute it and/or modify\n"
  "it under the terms of the GNU General Public License as published by\n"
  "the Free Software Foundation; either version 1, or (at your option)\n"
  "any later version - and this with the following clarification and\n"
  "special exception:\n"
  "\n"
  "   Linking this library statically or dynamically with other modules\n"
  "is making a combined work based on this library. Thus, the terms\n"
  "and conditions of the GNU General Public License cover the whole\n"
  "combination.\n"
  "\n"
  "   As a special exception, the copyright holders of this library\n"
  "give you permission to link this library with independent modules\n"
  "to produce an executable, regardless of the license terms of these\n"
  "independent modules, and to copy and distribute the resulting\n"
  "executable under terms of your choice, provided that you also meet,\n"
  "for each linked independent module, the terms and conditions of the\n"
  "license of that module. An independent module is a module which is\n"
  "not derived from or based on this library. If you modify this\n"
  "library, you may extend this exception to your version of the library,\n"
  "but you are not obliged to do so. If you do not wish to do so, delete\n"
  "this exception statement from your version.\n"
  "\n"
  "   OSLib is distributed in the hope that it will be useful,\n"
  "but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
  "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
  "GNU General Public License for more details.\n"
  "\n"
  "   You should have received a copy of the GNU General Public License\n"
  "along with this programme; if not, write to the Free Software\n"
  "Foundation, Inc, 675 Mass Ave, Cambridge, MA 02139, USA.\n";

