#ifndef ONCHIPMEM_INTERFACE_DEF_H
#define ONCHIPMEM_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.5.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct OCMIFace
{
	struct InterfaceData Data;

	ULONG APICALL (*Obtain)(struct OCMIFace *Self);
	ULONG APICALL (*Release)(struct OCMIFace *Self);
	void APICALL (*Expunge)(struct OCMIFace *Self);
	struct Interface * APICALL (*Clone)(struct OCMIFace *Self);
	ULONG * APICALL (*ObtainOnChipMem)(struct OCMIFace *Self);
	VOID APICALL (*ReleaseOnChipMem)(struct OCMIFace *Self);
	VOID APICALL (*CopyOnChipMem)(struct OCMIFace *Self, ULONG * source, ULONG * destination, ULONG size);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* ONCHIPMEM_INTERFACE_DEF_H */
