#ifndef INLINE4_ONCHIPMEM_H
#define INLINE4_ONCHIPMEM_H

/*
** This file was auto generated by idltool 53.5.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#include <interfaces/onchipmem.h>

/* Inline macros for Interface "main" */
#define ObtainOnChipMem() IOCM->ObtainOnChipMem() 
#define ReleaseOnChipMem() IOCM->ReleaseOnChipMem() 
#define CopyOnChipMem(source, destination, size) IOCM->CopyOnChipMem((source), (destination), (size)) 

#endif /* INLINE4_ONCHIPMEM_H */
